### ISSUE TITLE
OpenAPI.Net.OData link in README.md not working

### ISSUE THREAD

**Issue by DerGuteWolf** [microsoftgraph/microsoft-graph-openapi#4]
It points to https://github.com/Microsoft/OpenAPI.NET.OData for which I get a 404

**Comment by birbilis** [comment]
or maybe something like this: https://github.com/oasis-tcs/odata-openapi

**Comment by birbilis** [comment]
oops, sorry, meant this one: https://github.com/xuzhg/OData.OpenAPI (found from http://openapi.tools/)

**Comment by DerGuteWolf** [comment]
Well, obviously it didn't arrive there, whatever "moving to" means.  I would still ask the owner of this repo to correct to link to whereever he meant it should point to!

**Comment by xuzhg** [comment]
@DerGuteWolf @birbilis "https://github.com/microsoft/openapi.net.odata" is still in **Private** status, so that you maybe not access it. We are working to public it soon. Thanks.

**Comment by DerGuteWolf** [comment]
yes, thanks.  I will close this issue.
